### ISSUE TITLE
上传图片成功后返回的图片url错误

### ISSUE THREAD

**Issue by soulseen** [chengww5217/picgo-plugin-qingstor-uploader#1]
## 问题类型

Bug Report

## PicGo的相关信息

PicGo版本：2.0.3 和 2.0.4
OS: MacOS 10.14.3

## 问题重现

使用青云 qingstor插件上传成功图片后，显示的url错误。
![image](https://user-images.githubusercontent.com/16031013/55850680-f293dd00-5b87-11e9-8237-4dbe20047509.png)
<img width="797" alt="WechatIMG77" src="https://user-images.githubusercontent.com/16031013/55850770-6504bd00-5b88-11e9-8077-faf58a9f3303.png">
需要手动修改路径中的undefined才能显示
![image](https://user-images.githubusercontent.com/16031013/55850787-7bab1400-5b88-11e9-88b2-deb89e6195cb.png)

**Comment by chengww5217** [comment]
请在插件中更新 qingstor 插件后重启应用再试。如还不成功，请给出设置的 path

**Comment by soulseen** [comment]
更新重启都试了，path:png

**Comment by chengww5217** [comment]
现在重新上传一张图片还是一样的错误吗

**Comment by soulseen** [comment]
是的。更新重启后还是一样错误

**Comment by chengww5217** [comment]
非常抱歉，这是之前更新的一个 bug，请再次更新后重启。重新上传的图片就是正确路径的了。之前路径不正确只是本地的路径不正确，可以直接在本地相册中删除。

**Comment by soulseen** [comment]
已经修复了，非常感谢。
