### ISSUE TITLE
突然上传失败

### ISSUE THREAD

**Issue by mafeifan** [chengww5217/picgo-plugin-qingstor-uploader#3]
版本 PicGo 2.3.0
插件版本 1.2.1

2021-10-03 20:19:50 [PicGo ERROR] 
------Error Stack Begin------
**SyntaxError: Unexpected token E in JSON at position 0**
    at JSON.parse (<anonymous>)
    at Object.handleError (/Users/wang/Library/Application Support/picgo/node_modules/picgo-plugin-qingstor-uploader/dist/utils/index.js:97:23)
    at Object.handle (/Users/wang/Library/Application Support/picgo/node_modules/picgo-plugin-qingstor-uploader/dist/index.js:35:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 

打开堆栈中的文件，好像是try里面上传出错了，具体原因未知
![image](https://user-images.githubusercontent.com/4178463/135753803-fa4fafec-bec2-4970-affa-686e307e86cf.png)

**Comment by chengww5217** [comment]
嗯，这里程序解析错误有点问题，这种主要是网络问题或者配置填写的有问题，我这边先将这个错误修复下。

你这边需要检查下配置是不是正确。或者电脑是否有网。

**Comment by chengww5217** [comment]
比如 北京3区 有很多用户直接填写 `pek3`. 
`pek3` 是 region 可用区，代表一系列的 zones，需要在对象存储里面看下到底是 `pek3a` 、`pek3b`、`pek3d` 等

**Comment by chengww5217** [comment]
知道问题了。
1. 上传失败的原因：
  青云对象存储的证书有问题，虽然在网页上面是可用的，但是可能由于 picgo 使用 request 库版本原因导致证书识别有问题。
  解决办法：在`图床设置`->`青云Qingstor` -> `私有云(自定义)网址`中填写以下地址:
  `http://qingstor.com`
   以使用 http 地址上传，临时解决此问题。证书问题我会联系青云进行处理。

2. 插件没有提示正确的错误信息
     这个是异常解析的问题，已经在最新版本修复。进入`插件设置`-> `qingstor-uploader`->`更新插件` 后重启 picgo 即可。

**Comment by mafeifan** [comment]
> 知道问题了。
> 
> 1. 上传失败的原因：
>    青云对象存储的证书有问题，虽然在网页上面是可用的，但是可能由于 picgo 使用 request 库版本原因导致证书识别有问题。
>    解决办法：在`图床设置`->`青云Qingstor` -> `私有云(自定义)网址`中填写以下地址:
>    `http://qingstor.com`
>    以使用 http 地址上传，临时解决此问题。证书问题我会联系青云进行处理。
> 2. 插件没有提示正确的错误信息
>    这个是异常解析的问题，已经在最新版本修复。进入`插件设置`-> `qingstor-uploader`->`更新插件` 后重启 picgo 即可。

非常感谢！现在可以上传成功了！

**Comment by chengww5217** [comment]
出现证书问题的原因是青云对象存储 https 证书供应商 lets encrypt  的根证书 dst-root-ca-x3 在 9月30号的时候过期了，按照他们的预定计划，其根证书更换为了 ISRG Root X1 。具体参见：

https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

而 picgo 中的网络请求是基于 node js 的 request 库。nodejs ssl 根证书是内置的。仅下面这个提交的 node 版本才添加了 ISRG Root X1 到信任列表：
https://github.com/nodejs/node/commit/6331b63ce0e99bc1e5de4e21ea0c9da9df8ab759

所以 https 的问题暂时没法解决，需要 PicGo 升级 node 版本才行，这个问题先关闭了。

**Comment by chengww5217** [comment]
picgo 最新版本 [2.3.1-beta.2](https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.1-beta.2) 已经升级了 electron 版本，这样升级 picgo 就解决了 lets encrypt 证书问题。

此问题之前的兼容处理方式可以废弃了。直接将 私有云(自定义)网址 删除后保存即可。

https://github.com/Molunerfinn/PicGo/releases
