### ISSUE TITLE
如何在开发阶段测试正在开发的插件呢？

### ISSUE THREAD

**Issue by ChenSino** [chengww5217/picgo-plugin-qingstor-uploader#4]
如何在源码开发的时候测试呢？

**Comment by chengww5217** [comment]
参考 readme 里面的本地安装方法，本地安装源码，重启 picgo 即可

**Comment by chengww5217** [comment]
最新版本有导入本地插件的功能，直接导入本地插件就行了
<img width="800" alt="image" src="https://user-images.githubusercontent.com/34536334/157586673-78abd69a-7961-44bf-81ab-8a0e63ca4f01.png">

**Comment by ChenSino** [comment]
> 最新版本有导入本地插件的功能，直接导入本地插件就行了 <img alt="image" width="800" src="https://user-images.githubusercontent.com/34536334/157586673-78abd69a-7961-44bf-81ab-8a0e63ca4f01.png">

ok,谢谢
